

export const INIT_ETHJS = 'INIT_ETHJS';
export const INIT_KODA_CONTRACT = 'INIT_KODA_CONTRACT';

export const REFRESH_CONTRACT_DETAILS = 'REFRESH_CONTRACT_DETAILS';
export const REFRESH_ACCOUNT = 'REFRESH_ACCOUNT';


