// setup calls
export const INIT_KODA_CONTRACT = 'INIT_KODA_CONTRACT';

// contract calls
export const GET_ALL_ASSETS = 'GET_ALL_ASSETS';
export const REFRESH_CONTRACT_DETAILS = 'REFRESH_CONTRACT_DETAILS';
export const REFRESH_ACCOUNT = 'REFRESH_ACCOUNT';

export const PURCHASE_ASSET = 'PURCHASE_ASSET';


