

export const SET_ACCOUNT = 'SET_ACCOUNT';
export const SET_CURRENT_NETWORK = 'SET_CURRENT_NETWORK';

export const SET_ASSETS = 'SET_ASSETS';
export const SET_ARTISTS = 'SET_ARTISTS';

export const SET_CONTRACT_DETAILS = 'SET_CONTRACT_DETAILS';
export const SET_COMMISSION_ADDRESSES = 'SET_COMMISSION_ADDRESSES';

export const SET_TOTAL_PURCHASED = 'SET_TOTAL_PURCHASED';
