

export const SET_ACCOUNT = 'SET_ACCOUNT';
export const SET_CONTRACT = 'SET_CONTRACT';
export const SET_ETHJS = 'SET_ETHJS';
export const SET_CURATOR_ADDRESS = 'SET_CURATOR_ADDRESS';
export const SET_TOTAL_SUPPLY = 'SET_TOTAL_SUPPLY';
export const SET_TOTAL_PURCHASED = 'SET_TOTAL_PURCHASED';
export const SET_CONTRACT_DETAILS = 'SET_TOTAL_PURCHASED';
